BIEF <- BIEF %>% mutate(sexe = recode(as.character(sexe), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(iln = recode(as.character(iln), "1" = "En France (y compris outre-mer)", "2" = "À l'étranger"))
BIEF <- BIEF %>% mutate(inat1 = recode(as.character(inat1), "1" = "Française ? Oui", "2" = "Française ? Non"))
BIEF <- BIEF %>% mutate(inat2 = recode(as.character(inat2), "1" = "Étrangère ? Oui", "2" = "Étrangère ? Non"))
BIEF <- BIEF %>% mutate(inat3 = recode(as.character(inat3), "1" = "Né(e) français(e)", "2" = "Devenu(e) français(e)"))
BIEF <- BIEF %>% mutate(iran = recode(as.character(iran), "1" = "Dans le même logement que maintenant", "2" = "Dans un autre logement du même arrondissement/de la même commune (COM_LOC)", "3" = "En France, dans une autre commune (y compris outre-mer) ou un autre arrondissement", "4" = "À l'étranger"))
BIEF <- BIEF %>% mutate(autreresidence = recode(as.character(autreresidence), "1" = "Il/Elle vit dans un établissement mais ce logement reste sa résidence personnelle.", "2" = "Il/Elle est employé(e) de maison, salarié(e) ou jeune au pair et vit ici.", "3" = "Il/Elle vit la plus grande partie de l’année dans un autre logement mais vit temporairement ici au moment du recensement."))
BIEF <- BIEF %>% mutate(situat = recode(as.character(situat), "1" = "Emploi (salarié(e), à votre compte, vous travaillez sans être rémunéré(e) avec un membre de votre famille)", "NA" = "Y compris en congé maladie ou maternité, en congé parental de moins de 3 mois, en congé parental de plus de 3 moins avec un revenu compensatoire (Ex: Prepare) ou au chômage technique.", "2" = "Alternance en apprentissage", "3" = "Alternance en contrat de professionnalisation", "4" = "Études (élève, étudiant(e)) ou stage", "5" = "Chômage (inscrit(e) ou non à France Travail / Pôle emploi)", "6" = "Retraite ou préretraite", "7" = "Femme au foyer/Homme au foyer", "8" = "Autre situation"))
BIEF <- BIEF %>% mutate(sitrav = recode(as.character(sitrav), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(dejat = recode(as.character(dejat), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(rech = recode(as.character(rech), "1" = "Oui, depuis moins d'un an", "2" = "Oui, depuis un an ou plus", "3" = "Non"))
BIEF <- BIEF %>% mutate(etat = recode(as.character(etat), "1" = "à votre compte (y compris gérant(e) de société ou chef(fe) d’entreprise salarié(e)", "2" = "salarié(e) de la fonction publique (d’État, territoriale, hospitalière)", "3" = "salarié(e) d’un autre employeur (entreprise, association, particulier, etc.)", "4" = "non rémunéré(e) mais vous travaillez avec un membre de votre famille"))
BIEF <- BIEF %>% mutate(stat = recode(as.character(stat), "1" = "à votre compte (y compris gérant(e) de société ou chef(fe) d’entreprise salarié(e)", "2" = "salarié(e) de la fonction publique (d’État, territoriale, hospitalière)", "3" = "salarié(e) d’un autre employeur (entreprise, association, particulier, etc.)", "4" = "non rémunéré(e) mais vous travaillez avec un membre de votre famille"))
BIEF <- BIEF %>% mutate(interim = recode(as.character(interim), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(trans = recode(as.character(trans), "1" = "Pas de déplacement", "2" = "Marche à pied, rollers ou trottinette", "3" = "Vélo (y compris à assistance électrique)", "4" = "Deux-roues motorisé", "5" = "Voiture, camion ou fourgonnette", "6" = "Transports en commun"))
BIEF <- BIEF %>% mutate(teletravail = recode(as.character(teletravail), "1" = "Jamais", "2" = "Quelques jours par mois", "3" = "Un jour par semaine", "4" = "Deux jours par semaine", "5" = "Trois jours par semaine ou plus"))
BIEF <- BIEF %>% mutate(tp = recode(as.character(tp), "1" = "à temps complet", "2" = "à temps partiel à 80 % ou plus", "3" = "à temps partiel à moins de 80 %"))
BIEF <- BIEF %>% mutate(empl = recode(as.character(empl), "1" = "CDI (contrat à durée indéterminée) ou fonctionnaire", "2" = "Autre contrat (CDD, intérim, stage, etc.) de 3 mois ou plus", "3" = "Autre contrat (CDD, intérim, stage, etc.) de moins de 3 mois"))
BIEF <- BIEF %>% mutate(vardompart = recode(as.character(vardompart), "1" = "fixe, en dehors de votre domicile (hors télétravail)", "2" = "variable", "3" = "fixe, exclusivement à votre domicile"))
BIEF <- BIEF %>% mutate(ilt = recode(as.character(ilt), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ilt2 = recode(as.character(ilt2), "1" = "En France", "2" = "À l’étranger"))
BIEF <- BIEF %>% mutate(statav = recode(as.character(statav), "1" = "à votre compte (y compris gérant(e) de société ou chef(fe) d’entreprise salarié(e)", "2" = "salarié(e) de la fonction publique (d’État, territoriale, hospitalière)", "3" = "salarié(e) d’un autre employeur (entreprise, association, particulier, etc.)", "4" = "non rémunéré(e) mais vous travailliez avec un membre de votre famille"))
BIEF <- BIEF %>% mutate(nbsal = recode(as.character(nbsal), "1" = "Une seule personne, vous travaillez seul(e)", "2" = "Entre 2 et 10 personnes", "3" = "Entre 11 et 49 personnes", "4" = "50 personnes ou plus"))
BIEF <- BIEF %>% mutate(posp = recode(as.character(posp), "1" = "manœuvre, ouvrier(ouvrière) spécialisé(e)", "2" = "ouvrier(ouvrière) qualifié(e), technicien(technicienne) d'atelier", "3" = "employé(e) de bureau, de commerce, de services", "4" = "agent(e) de maîtrise (y compris administrative ou commerciale)", "5" = "technicien(ne)", "6" = "ingénieur(e), cadre d'entreprise", "7" = "agent(e) de catégorie C de la fonction publique", "8" = "agent(e) de catégorie B de la fonction publique", "9" = "agent(e) de catégorie A de la fonction publique", "10" = "dans une autre situation"))
BIEF <- BIEF %>% mutate(gali = recode(as.character(gali), "1" = "Oui, fortement limité(e)", "2" = "Oui, limité(e) mais pas fortement", "3" = "Non, pas limité(e)", "4" = "Je ne souhaite pas répondre"))
BIEF <- BIEF %>% mutate(etud = recode(as.character(etud), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(etude_dist = recode(as.character(etude_dist), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(iletu = recode(as.character(iletu), "1" = "Dans le même arrondissement/la même commune que votre logement (COM_LOC)", "2" = "En France, dans une autre commune ou un autre arrondissement", "3" = "À l'étranger"))
BIEF <- BIEF %>% mutate(dipl = recode(as.character(dipl), "1" = "Aucun diplôme", "2" = "CEP (certificat d’études primaires)", "3" = "BEPC, brevet élémentaire, brevet des collèges, DNB", "4" = "CAP, BEP ou diplôme de niveau équivalent", "5" = "Baccalauréat général ou technologique, brevet supérieur", "6" = "Baccalauréat professionnel, brevet professionnel, de technicien ou d’enseignement, diplôme équivalent", "7" = "Capacité en droit, DAEU, ESEU", "8" = "BTS, DUT, Deug, Deust, diplôme de la santé ou du social de niveau bac+2, diplôme équivalent", "9" = "Licence, licence pro, BUT, maîtrise, diplôme équivalent de niveau bac+3 ou bac+4", "10" = "Master, DEA, DESS, diplôme grande école niveau bac+5, doctorat de santé", "11" = "Doctorat de recherche (hors santé)"))
BIEF <- BIEF %>% mutate(niv_etud = recode(as.character(niv_etud), "1" = "Vous êtes en cours d’études.", "2" = "Vous n'êtes jamais allé(e) à l’école ou vous l’avez quittée avant la fin du primaire.", "3" = "Vous avez interrompu votre scolarité à la fin du primaire ou avant la fin du collège.", "4" = "Vous avez suivi votre scolarité jusqu’à la fin du collège ou au-delà."))
BIEF <- BIEF %>% mutate(couple = recode(as.character(couple), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(matr = recode(as.character(matr), "1" = "Marié(e)", "2" = "Pacsé(e)", "3" = "En concubinage ou union libre", "4" = "Veu(veuve)", "5" = "Divorcé(e)", "6" = "Célibataire"))
BIEF <- BIEF %>% mutate(nai_p1 = recode(as.character(nai_p1), "1" = "En France", "2" = "À l’étranger", "3" = "Je ne sais pas", "4" = "Je ne souhaite pas répondre"))
BIEF <- BIEF %>% mutate(nai_p2 = recode(as.character(nai_p2), "1" = "En France", "2" = "À l’étranger", "3" = "Je ne sais pas", "4" = "Je ne souhaite pas répondre"))
BIEF <- BIEF %>% mutate(SEPARE = recode(as.character(SEPARE), "1" = "...vous vous êtes séparé(e)s", "2" = "... votre dernier(ère) conjoint(e) est décédé(e)"))
BIEF <- BIEF %>% mutate(HEBERG = recode(as.character(HEBERG), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(TRAVACT = recode(as.character(TRAVACT), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DEJATRAV1 = recode(as.character(DEJATRAV1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DEJATRAV2 = recode(as.character(DEJATRAV2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(COUPLE = recode(as.character(COUPLE), "1" = "Oui, avec quelqu'un qui vit avec vous dans ce logement", "2" = "Oui, avec quelqu'un qui vit dans un autre logement", "3" = "Non, mais vous avez déjà été en couple par le passé", "4" = "Non, vous n'avez jamais été en couple"))
BIEF <- BIEF %>% mutate(PACS = recode(as.character(PACS), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(MARI = recode(as.character(MARI), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_UNION = recode(as.character(AUT_UNION), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ENF = recode(as.character(ENF), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NBENF_ADOP_UN = recode(as.character(NBENF_ADOP_UN), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NBENFLOG_UN = recode(as.character(NBENFLOG_UN), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NBENFLOG = recode(as.character(NBENFLOG), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NBENFAIL_UN = recode(as.character(NBENFAIL_UN), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(FINETU = recode(as.character(FINETU), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(VECU_PLACE = recode(as.character(VECU_PLACE), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE2_ENFE = recode(as.character(LANGUE2_ENFE), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE3_ENFE = recode(as.character(LANGUE3_ENFE), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE4_ENFE = recode(as.character(LANGUE4_ENFE), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE1_ENTOUE = recode(as.character(LANGUE1_ENTOUE), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE2_ENTOUE = recode(as.character(LANGUE2_ENTOUE), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE3_ENTOUE = recode(as.character(LANGUE3_ENTOUE), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_C = recode(as.character(SEXE_C), "1" = "Un homme", "2" = "Une femme"))
BIEF <- BIEF %>% mutate(LIEUNAIS_C = recode(as.character(LIEUNAIS_C), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(STATUT_C = recode(as.character(STATUT_C), "1" = "A son compte (y compris gérant(e) de société salarié(e))", "2" = "Salarié(e) de la fonction publique (Etat, territoriale, hospitalière)", "3" = "Salarié(e) d'une entreprise (y compris d'une association ou de la sécurité sociale)", "4" = "Salarié(e) d'un particulier", "5" = "Aide familial(e) non rémunéré(e)"))
BIEF <- BIEF %>% mutate(ENFAV_C = recode(as.character(ENFAV_C), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NBENFAV_VENU_C1 = recode(as.character(NBENFAV_VENU_C1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ENF21_AUTPAR_C1 = recode(as.character(ENF21_AUTPAR_C1), "NA" = "Non - Non"))
BIEF <- BIEF %>% mutate(ENF21_AUTPAR_C2 = recode(as.character(ENF21_AUTPAR_C2), "NA" = "Non - Non"))
BIEF <- BIEF %>% mutate(ENF21_AUTPAR_C3 = recode(as.character(ENF21_AUTPAR_C3), "NA" = "Non - Non"))
BIEF <- BIEF %>% mutate(ENF21_AUTPAR_C4 = recode(as.character(ENF21_AUTPAR_C4), "NA" = "Non - Non"))
BIEF <- BIEF %>% mutate(PACS_U1 = recode(as.character(PACS_U1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(MARI_U1 = recode(as.character(MARI_U1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEPARE_U1 = recode(as.character(SEPARE_U1), "1" = "...vous vous êtes séparé(e)s", "2" = "... votre premier(ère) conjoint(e) est décédé(e)"))
BIEF <- BIEF %>% mutate(ENFAV_C_U1 = recode(as.character(ENFAV_C_U1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NBENFAV_C1_VENU_U1 = recode(as.character(NBENFAV_C1_VENU_U1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PACS_U2 = recode(as.character(PACS_U2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(MARI_U2 = recode(as.character(MARI_U2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEPARE_U2 = recode(as.character(SEPARE_U2), "1" = "...vous vous êtes séparé(e)s", "2" = "... votre premier(ère) conjoint(e) est décédé(e)"))
BIEF <- BIEF %>% mutate(ENFAV_C_U2 = recode(as.character(ENFAV_C_U2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NBENFAV_C1_VENU_U2 = recode(as.character(NBENFAV_C1_VENU_U2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG1 = recode(as.character(SEXE_ENFLOG1), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG1 = recode(as.character(NEFRANCE_ENFLOG1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG1 = recode(as.character(PARENT_VIT_ENFLOG1), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG1 = recode(as.character(PARENT_FR_ENFLOG1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG1 = recode(as.character(PARENT_FREQ_ENFLOG1), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG1 = recode(as.character(PARENT_DORT_ENFLOG1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG1 = recode(as.character(PARENT_VECU_ENFLOG1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG1 = recode(as.character(SEP_AUT_PAR_ENFLOG1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG1 = recode(as.character(RESID_ENFLOG1), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG1 = recode(as.character(SANTE_ENFLOG1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG1 = recode(as.character(ASE_ENFLOG1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG2 = recode(as.character(SEXE_ENFLOG2), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG2 = recode(as.character(NEFRANCE_ENFLOG2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG2 = recode(as.character(PARENT_VIT_ENFLOG2), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG2 = recode(as.character(PARENT_FR_ENFLOG2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG2 = recode(as.character(PARENT_FREQ_ENFLOG2), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG2 = recode(as.character(PARENT_DORT_ENFLOG2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG2 = recode(as.character(PARENT_VECU_ENFLOG2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG2 = recode(as.character(SEP_AUT_PAR_ENFLOG2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG2 = recode(as.character(RESID_ENFLOG2), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG2 = recode(as.character(SANTE_ENFLOG2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG2 = recode(as.character(ASE_ENFLOG2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG3 = recode(as.character(SEXE_ENFLOG3), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG3 = recode(as.character(NEFRANCE_ENFLOG3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG3 = recode(as.character(PARENT_VIT_ENFLOG3), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG3 = recode(as.character(PARENT_FR_ENFLOG3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG3 = recode(as.character(PARENT_FREQ_ENFLOG3), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG3 = recode(as.character(PARENT_DORT_ENFLOG3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG3 = recode(as.character(PARENT_VECU_ENFLOG3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG3 = recode(as.character(SEP_AUT_PAR_ENFLOG3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG3 = recode(as.character(RESID_ENFLOG3), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG3 = recode(as.character(SANTE_ENFLOG3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG3 = recode(as.character(ASE_ENFLOG3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG4 = recode(as.character(SEXE_ENFLOG4), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG4 = recode(as.character(NEFRANCE_ENFLOG4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG4 = recode(as.character(PARENT_VIT_ENFLOG4), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG4 = recode(as.character(PARENT_FR_ENFLOG4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG4 = recode(as.character(PARENT_FREQ_ENFLOG4), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG4 = recode(as.character(PARENT_DORT_ENFLOG4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG4 = recode(as.character(PARENT_VECU_ENFLOG4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG4 = recode(as.character(SEP_AUT_PAR_ENFLOG4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG4 = recode(as.character(RESID_ENFLOG4), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG4 = recode(as.character(SANTE_ENFLOG4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG4 = recode(as.character(ASE_ENFLOG4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG5 = recode(as.character(SEXE_ENFLOG5), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG5 = recode(as.character(NEFRANCE_ENFLOG5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG5 = recode(as.character(PARENT_VIT_ENFLOG5), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG5 = recode(as.character(PARENT_FR_ENFLOG5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG5 = recode(as.character(PARENT_FREQ_ENFLOG5), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG5 = recode(as.character(PARENT_DORT_ENFLOG5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG5 = recode(as.character(PARENT_VECU_ENFLOG5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG5 = recode(as.character(SEP_AUT_PAR_ENFLOG5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG5 = recode(as.character(RESID_ENFLOG5), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG5 = recode(as.character(SANTE_ENFLOG5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG5 = recode(as.character(ASE_ENFLOG5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG6 = recode(as.character(SEXE_ENFLOG6), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG6 = recode(as.character(NEFRANCE_ENFLOG6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG6 = recode(as.character(PARENT_VIT_ENFLOG6), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG6 = recode(as.character(PARENT_FR_ENFLOG6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG6 = recode(as.character(PARENT_FREQ_ENFLOG6), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG6 = recode(as.character(PARENT_DORT_ENFLOG6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG6 = recode(as.character(PARENT_VECU_ENFLOG6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG6 = recode(as.character(SEP_AUT_PAR_ENFLOG6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG6 = recode(as.character(RESID_ENFLOG6), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG6 = recode(as.character(SANTE_ENFLOG6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG6 = recode(as.character(ASE_ENFLOG6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG7 = recode(as.character(SEXE_ENFLOG7), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG7 = recode(as.character(NEFRANCE_ENFLOG7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG7 = recode(as.character(PARENT_VIT_ENFLOG7), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG7 = recode(as.character(PARENT_FR_ENFLOG7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG7 = recode(as.character(PARENT_FREQ_ENFLOG7), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG7 = recode(as.character(PARENT_DORT_ENFLOG7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG7 = recode(as.character(PARENT_VECU_ENFLOG7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG7 = recode(as.character(SEP_AUT_PAR_ENFLOG7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG7 = recode(as.character(RESID_ENFLOG7), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG7 = recode(as.character(SANTE_ENFLOG7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG7 = recode(as.character(ASE_ENFLOG7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFLOG8 = recode(as.character(SEXE_ENFLOG8), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFLOG8 = recode(as.character(NEFRANCE_ENFLOG8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFLOG8 = recode(as.character(PARENT_VIT_ENFLOG8), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_FR_ENFLOG8 = recode(as.character(PARENT_FR_ENFLOG8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFLOG8 = recode(as.character(PARENT_FREQ_ENFLOG8), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(PARENT_DORT_ENFLOG8 = recode(as.character(PARENT_DORT_ENFLOG8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFLOG8 = recode(as.character(PARENT_VECU_ENFLOG8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFLOG8 = recode(as.character(SEP_AUT_PAR_ENFLOG8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFLOG8 = recode(as.character(RESID_ENFLOG8), "2" = "Pas de décision de justice", "3" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "4" = "Principalement chez vous", "5" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFLOG8 = recode(as.character(SANTE_ENFLOG8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFLOG8 = recode(as.character(ASE_ENFLOG8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL1 = recode(as.character(SEXE_ENFAIL1), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL1 = recode(as.character(NEFRANCE_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL1 = recode(as.character(PARENT_VIT_ENFAIL1), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL1 = recode(as.character(PARENT_VECU_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL1 = recode(as.character(DC_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL1 = recode(as.character(PARENT_FREQ_ENFAIL1), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL1 = recode(as.character(FR_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL1 = recode(as.character(LOG_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL1 = recode(as.character(AUT_PAR_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL1 = recode(as.character(DORT_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL1 = recode(as.character(SEP_AUT_PAR_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL1 = recode(as.character(RESID_ENFAIL1), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL1 = recode(as.character(SANTE_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL1 = recode(as.character(ASE_ENFAIL1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL2 = recode(as.character(SEXE_ENFAIL2), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL2 = recode(as.character(NEFRANCE_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL2 = recode(as.character(PARENT_VIT_ENFAIL2), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL2 = recode(as.character(PARENT_VECU_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL2 = recode(as.character(DC_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL2 = recode(as.character(PARENT_FREQ_ENFAIL2), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL2 = recode(as.character(FR_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL2 = recode(as.character(LOG_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL2 = recode(as.character(AUT_PAR_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL2 = recode(as.character(DORT_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL2 = recode(as.character(SEP_AUT_PAR_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL2 = recode(as.character(RESID_ENFAIL2), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL2 = recode(as.character(SANTE_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL2 = recode(as.character(ASE_ENFAIL2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL3 = recode(as.character(SEXE_ENFAIL3), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL3 = recode(as.character(NEFRANCE_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL3 = recode(as.character(PARENT_VIT_ENFAIL3), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL3 = recode(as.character(PARENT_VECU_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL3 = recode(as.character(DC_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL3 = recode(as.character(PARENT_FREQ_ENFAIL3), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL3 = recode(as.character(FR_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL3 = recode(as.character(LOG_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL3 = recode(as.character(AUT_PAR_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL3 = recode(as.character(DORT_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL3 = recode(as.character(SEP_AUT_PAR_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL3 = recode(as.character(RESID_ENFAIL3), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL3 = recode(as.character(SANTE_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL3 = recode(as.character(ASE_ENFAIL3), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL4 = recode(as.character(SEXE_ENFAIL4), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL4 = recode(as.character(NEFRANCE_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL4 = recode(as.character(PARENT_VIT_ENFAIL4), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL4 = recode(as.character(PARENT_VECU_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL4 = recode(as.character(DC_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL4 = recode(as.character(PARENT_FREQ_ENFAIL4), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL4 = recode(as.character(FR_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL4 = recode(as.character(LOG_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL4 = recode(as.character(AUT_PAR_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL4 = recode(as.character(DORT_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL4 = recode(as.character(SEP_AUT_PAR_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL4 = recode(as.character(RESID_ENFAIL4), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL4 = recode(as.character(SANTE_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL4 = recode(as.character(ASE_ENFAIL4), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL5 = recode(as.character(SEXE_ENFAIL5), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL5 = recode(as.character(NEFRANCE_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL5 = recode(as.character(PARENT_VIT_ENFAIL5), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL5 = recode(as.character(PARENT_VECU_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL5 = recode(as.character(DC_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL5 = recode(as.character(PARENT_FREQ_ENFAIL5), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL5 = recode(as.character(FR_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL5 = recode(as.character(LOG_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL5 = recode(as.character(AUT_PAR_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL5 = recode(as.character(DORT_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL5 = recode(as.character(SEP_AUT_PAR_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL5 = recode(as.character(RESID_ENFAIL5), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL5 = recode(as.character(SANTE_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL5 = recode(as.character(ASE_ENFAIL5), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL6 = recode(as.character(SEXE_ENFAIL6), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL6 = recode(as.character(NEFRANCE_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL6 = recode(as.character(PARENT_VIT_ENFAIL6), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL6 = recode(as.character(PARENT_VECU_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL6 = recode(as.character(DC_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL6 = recode(as.character(PARENT_FREQ_ENFAIL6), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL6 = recode(as.character(FR_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL6 = recode(as.character(LOG_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL6 = recode(as.character(AUT_PAR_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL6 = recode(as.character(DORT_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL6 = recode(as.character(SEP_AUT_PAR_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL6 = recode(as.character(RESID_ENFAIL6), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL6 = recode(as.character(SANTE_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL6 = recode(as.character(ASE_ENFAIL6), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL7 = recode(as.character(SEXE_ENFAIL7), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL7 = recode(as.character(NEFRANCE_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL7 = recode(as.character(PARENT_VIT_ENFAIL7), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL7 = recode(as.character(PARENT_VECU_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL7 = recode(as.character(DC_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL7 = recode(as.character(PARENT_FREQ_ENFAIL7), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL7 = recode(as.character(FR_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL7 = recode(as.character(LOG_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL7 = recode(as.character(AUT_PAR_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL7 = recode(as.character(DORT_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL7 = recode(as.character(SEP_AUT_PAR_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL7 = recode(as.character(RESID_ENFAIL7), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL7 = recode(as.character(SANTE_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL7 = recode(as.character(ASE_ENFAIL7), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_ENFAIL8 = recode(as.character(SEXE_ENFAIL8), "1" = "Masculin", "2" = "Féminin"))
BIEF <- BIEF %>% mutate(NEFRANCE_ENFAIL8 = recode(as.character(NEFRANCE_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_VIT_ENFAIL8 = recode(as.character(PARENT_VIT_ENFAIL8), "1" = "Oui, il/elle vit avec vous", "2" = "Non, il/elle vit ailleurs", "3" = "Non, il/elle est décédé(e)", "4" = "Je ne sais pas Questionnaire BVA : « Vous ne savez pas »", "5" = "Il n'y a pas d'autre parent"))
BIEF <- BIEF %>% mutate(PARENT_VECU_ENFAIL8 = recode(as.character(PARENT_VECU_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DC_ENFAIL8 = recode(as.character(DC_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PARENT_FREQ_ENFAIL8 = recode(as.character(PARENT_FREQ_ENFAIL8), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(FR_ENFAIL8 = recode(as.character(FR_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_ENFAIL8 = recode(as.character(LOG_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(AUT_PAR_ENFAIL8 = recode(as.character(AUT_PAR_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(DORT_ENFAIL8 = recode(as.character(DORT_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEP_AUT_PAR_ENFAIL8 = recode(as.character(SEP_AUT_PAR_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(RESID_ENFAIL8 = recode(as.character(RESID_ENFAIL8), "1" = "Pas de décision de justice", "2" = "La moitié du temps chez chaque parentQuestionnaire BVA : « La moitié du temps chez chaque parent (garde alternée) »", "3" = "Principalement chez vous", "4" = "Principalement chez son autre parent"))
BIEF <- BIEF %>% mutate(SANTE_ENFAIL8 = recode(as.character(SANTE_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ASE_ENFAIL8 = recode(as.character(ASE_ENFAIL8), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_PAR1 = recode(as.character(SEXE_PAR1), "1" = "Une femme", "2" = "Un homme"))
BIEF <- BIEF %>% mutate(NATIO_PAR1 = recode(as.character(NATIO_PAR1), "1" = "Oui", "2" = "Non", "3" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "4" = "Je ne souhaite pas répondreQuestionnaire BVA : « Vous ne souhaitez pas répondre »"))
BIEF <- BIEF %>% mutate(TRAV_PAR1 = recode(as.character(TRAV_PAR1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(STATUT_PAR1 = recode(as.character(STATUT_PAR1), "1" = "A son compte (y compris gérant(e) de société salarié(e)", "2" = "Salarié(e) de la fonction publique (Etat, territoriale, hospitalière)", "3" = "Salarié(e) d'une entreprise (y compris d'une association ou de la sécurité sociale)", "4" = "Salarié(e) d'un particulier", "5" = "Aide familial(e) non rémunéré(e)", "6" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »"))
BIEF <- BIEF %>% mutate(VIV_PAR1 = recode(as.character(VIV_PAR1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_PAR1 = recode(as.character(LOG_PAR1), "1" = "Avec vous, dans ce logement", "2" = "Ailleurs"))
BIEF <- BIEF %>% mutate(FR_PAR1 = recode(as.character(FR_PAR1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ETAB_PAR1 = recode(as.character(ETAB_PAR1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(FREQ_VU_PAR1 = recode(as.character(FREQ_VU_PAR1), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(EXIST_PAR2 = recode(as.character(EXIST_PAR2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(SEXE_PAR2 = recode(as.character(SEXE_PAR2), "1" = "Une femme", "2" = "Un homme"))
BIEF <- BIEF %>% mutate(NATIO_PAR2 = recode(as.character(NATIO_PAR2), "1" = "Oui", "2" = "Non", "3" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »", "4" = "Je ne souhaite pas répondreQuestionnaire BVA : « Vous ne souhaitez pas répondre »"))
BIEF <- BIEF %>% mutate(TRAV_PAR2 = recode(as.character(TRAV_PAR2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(STATUT_PAR2 = recode(as.character(STATUT_PAR2), "1" = "A son compte (y compris gérant(e) de société salarié(e)", "2" = "Salarié(e) de la fonction publique (Etat, territoriale, hospitalière)", "3" = "Salarié(e) d'une entreprise (y compris d'une association ou de la sécurité sociale)", "4" = "Salarié(e) d'un particulier", "5" = "Aide familial(e) non rémunéré(e)", "6" = "Je ne sais pasQuestionnaire BVA : « Vous ne savez pas »"))
BIEF <- BIEF %>% mutate(VIV_PAR2 = recode(as.character(VIV_PAR2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(FR_PAR2 = recode(as.character(FR_PAR2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(ETAB_PAR2 = recode(as.character(ETAB_PAR2), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(FREQ_VU_PAR2 = recode(as.character(FREQ_VU_PAR2), "1" = "Une ou plusieurs fois par semaine", "2" = "Une ou plusieurs fois par mois", "3" = "Une ou plusieurs fois par an", "4" = "Plus rarement ou jamais"))
BIEF <- BIEF %>% mutate(LANGUE2_PAR1E = recode(as.character(LANGUE2_PAR1E), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE3_PAR1E = recode(as.character(LANGUE3_PAR1E), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE4_PAR1E = recode(as.character(LANGUE4_PAR1E), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE2_PAR2E = recode(as.character(LANGUE2_PAR2E), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE3_PAR2E = recode(as.character(LANGUE3_PAR2E), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LANGUE4_PAR2E = recode(as.character(LANGUE4_PAR2E), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(LOG_PAR2B = recode(as.character(LOG_PAR2B), "1" = "Avec vous, dans ce logement", "2" = "Ailleurs"))
BIEF <- BIEF %>% mutate(NB_FRERES_VIV1 = recode(as.character(NB_FRERES_VIV1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(NB_SOEURS_VIV1 = recode(as.character(NB_SOEURS_VIV1), "1" = "Oui", "2" = "Non"))
BIEF <- BIEF %>% mutate(PETIT_ENF = recode(as.character(PETIT_ENF), "1" = "Oui", "2" = "Non"))
